providers=["node","staticfile"]

[phases.setup]
nixPkgs = ['bun']

[phases.install]
cmds = ['bun i --no-save']

[phases.build]
cmds = ['bun run build']

[[ nixpacks.included_files ]]
paths = [".vitepress/dist"]
