import { Vuepress } from '@vuepress/client/lib/components/Vuepress'

const routeItems = [
  ["v-303d92de","/NOTES.html",{"title":"Notes sur les temps sur chaque « cours »"},["/NOTES","/NOTES.md"]],
  ["v-8daa1a0e","/",{"title":"Support de Cours & TP"},["/index.html","/README.md"]],
  ["v-6c83e5e4","/concours/",{"title":""},["/concours/index.html","/concours/index.md"]],
  ["v-941f25fe","/cheatsheets/",{"title":"Aide mémoire"},["/cheatsheets/index.html","/cheatsheets/README.md"]],
  ["v-253f9046","/pages/contact.html",{"title":"Une question ?"},["/pages/contact","/pages/contact.md"]],
  ["v-952bdb0c","/cours/android_base.html",{"title":"Slides Android Base"},["/cours/android_base","/cours/android_base.md"]],
  ["v-5a38a44c","/cours/android_ble.html",{"title":"Slides Android + BLE"},["/cours/android_ble","/cours/android_ble.md"]],
  ["v-2c668b23","/cours/android_http.html",{"title":"Slides Android + HTTP"},["/cours/android_http","/cours/android_http.md"]],
  ["v-72b228d8","/cours/cicd.html",{"title":"CI/CD"},["/cours/cicd","/cours/cicd.md"]],
  ["v-493a027b","/cours/cordova.html",{"title":"Slides Cordova"},["/cours/cordova","/cours/cordova.md"]],
  ["v-490a93db","/cours/docker.html",{"title":"Slides Docker"},["/cours/docker","/cours/docker.md"]],
  ["v-3041ce26","/cours/framework_javascript.html",{"title":"Slides Framework JavaScript"},["/cours/framework_javascript","/cours/framework_javascript.md"]],
  ["v-0a63ba65","/cours/git.html",{"title":"Slides Git"},["/cours/git","/cours/git.md"]],
  ["v-c0f3cb40","/cours/gitlab.html",{"title":"Slides Gitlab"},["/cours/gitlab","/cours/gitlab.md"]],
  ["v-7028d00c","/cours/gitlabci.html",{"title":"Slides Gitlab-ci"},["/cours/gitlabci","/cours/gitlabci.md"]],
  ["v-3d77c826","/cours/introduction_api.html",{"title":"Slides Introduction API"},["/cours/introduction_api","/cours/introduction_api.md"]],
  ["v-706a0203","/cours/introduction_html_css.html",{"title":"Slides HTML et CSS"},["/cours/introduction_html_css","/cours/introduction_html_css.md"]],
  ["v-a21b8ef6","/cours/introduction_javascript.html",{"title":"Slides Javascript"},["/cours/introduction_javascript","/cours/introduction_javascript.md"]],
  ["v-8f2d08f0","/cours/introduction_php.html",{"title":"Slides introduction PHP"},["/cours/introduction_php","/cours/introduction_php.md"]],
  ["v-e0b37734","/cours/introduction_securite.html",{"title":"Slides introduction développement sécurisé (OWASP)"},["/cours/introduction_securite","/cours/introduction_securite.md"]],
  ["v-5c30a94e","/cours/introduction_sql_php.html",{"title":"Slides introduction aux BDD avec PHP"},["/cours/introduction_sql_php","/cours/introduction_sql_php.md"]],
  ["v-29f58804","/cours/javascript_avances.html",{"title":"Slides Javascript avancés"},["/cours/javascript_avances","/cours/javascript_avances.md"]],
  ["v-13cd58de","/cours/laravel.html",{"title":"Slides Laravel"},["/cours/laravel","/cours/laravel.md"]],
  ["v-d6d8c488","/cours/les_interfaces.html",{"title":"Slides Les Interfaces"},["/cours/les_interfaces","/cours/les_interfaces.md"]],
  ["v-0c59675d","/cours/mvc.html",{"title":"Le design pattern MVC"},["/cours/mvc","/cours/mvc.md"]],
  ["v-492af210","/cours/nodejs.html",{"title":"Slides NodeJS"},["/cours/nodejs","/cours/nodejs.md"]],
  ["v-3d4b2384","/cours/organisations.html",{"title":"Slides Organisations"},["/cours/organisations","/cours/organisations.md"]],
  ["v-33a912b2","/cours/poo.html",{"title":"Slides POO la Programmation Orientée Objet"},["/cours/poo","/cours/poo.md"]],
  ["v-79b4269f","/cours/python.html",{"title":"Slides Python"},["/cours/python","/cours/python.md"]],
  ["v-bb8a9c3e","/cours/securite_applications.html",{"title":"Slides Securité des applications"},["/cours/securite_applications","/cours/securite_applications.md"]],
  ["v-09d84b96","/cours/typescript.html",{"title":"Slides Typescript"},["/cours/typescript","/cours/typescript.md"]],
  ["v-bae2d8f0","/cours/vuejs.html",{"title":"Slides VueJS"},["/cours/vuejs","/cours/vuejs.md"]],
  ["v-2d0abf9a","/tp/",{"title":"Introduction"},["/tp/index.html","/tp/README.md"]],
  ["v-619dc8b4","/cheatsheets/cordova/",{"title":""},["/cheatsheets/cordova/index.html","/cheatsheets/cordova/README.md"]],
  ["v-710a75ee","/cheatsheets/docker/",{"title":"Aide mémoire Docker"},["/cheatsheets/docker/index.html","/cheatsheets/docker/README.md"]],
  ["v-3e306f1e","/cheatsheets/git/",{"title":"Aide mémoire GIT"},["/cheatsheets/git/index.html","/cheatsheets/git/README.md"]],
  ["v-44dc1896","/cheatsheets/git/commit_template.html",{"title":""},["/cheatsheets/git/commit_template","/cheatsheets/git/commit_template.md"]],
  ["v-f01f0cfa","/cheatsheets/html/",{"title":"Aide mémoire HTML"},["/cheatsheets/html/index.html","/cheatsheets/html/README.md"]],
  ["v-3c626cc1","/cheatsheets/javascript/",{"title":"Aide mémoire JavaScript"},["/cheatsheets/javascript/index.html","/cheatsheets/javascript/README.md"]],
  ["v-fb94d0cc","/cheatsheets/owasp/",{"title":"La méthode OWASP"},["/cheatsheets/owasp/index.html","/cheatsheets/owasp/README.md"]],
  ["v-3e348238","/cheatsheets/php/",{"title":"Aide mémoire PHP"},["/cheatsheets/php/index.html","/cheatsheets/php/README.md"]],
  ["v-23c9c897","/cheatsheets/laravel/",{"title":"Laravel 8"},["/cheatsheets/laravel/index.html","/cheatsheets/laravel/README.md"]],
  ["v-3e349c60","/cheatsheets/poo/",{"title":"La syntaxe Objet"},["/cheatsheets/poo/index.html","/cheatsheets/poo/README.md"]],
  ["v-c02bd98e","/cheatsheets/poo-uml/",{"title":"La modélisation objet"},["/cheatsheets/poo-uml/index.html","/cheatsheets/poo-uml/README.md"]],
  ["v-3e3600a2","/cheatsheets/sql/",{"title":"Aide mémoire SQL"},["/cheatsheets/sql/index.html","/cheatsheets/sql/README.md"]],
  ["v-e3e5f5fe","/cheatsheets/vuejs/",{"title":"Aide mémoire VueJS 2.0"},["/cheatsheets/vuejs/index.html","/cheatsheets/vuejs/README.md"]],
  ["v-53d4bfb9","/tp/android/android-base-tp.html",{"title":"Découverte des bases d'Android"},["/tp/android/android-base-tp","/tp/android/android-base-tp.md"]],
  ["v-7da809b9","/tp/android/android-base2-tp.html",{"title":"Suite découverte des bases d'Android"},["/tp/android/android-base2-tp","/tp/android/android-base2-tp.md"]],
  ["v-7b96a7cd","/tp/android/app-avance-android.html",{"title":"Application Client / Serveur"},["/tp/android/app-avance-android","/tp/android/app-avance-android.md"]],
  ["v-84a060c0","/tp/android/app-base-android.html",{"title":"Android base : Projet final"},["/tp/android/app-base-android","/tp/android/app-base-android.md"]],
  ["v-49f7b503","/tp/android/app-ble-network.html",{"title":"Télécommande Bluetooth & Réseau"},["/tp/android/app-ble-network","/tp/android/app-ble-network.md"]],
  ["v-797029a5","/tp/android/network.html",{"title":"Appeler une API simplement"},["/tp/android/network","/tp/android/network.md"]],
  ["v-e9ae5b54","/tp/android/sample-explication.html",{"title":"Explication structure « Android Boilerplate »"},["/tp/android/sample-explication","/tp/android/sample-explication.md"]],
  ["v-8e9ba06e","/tp/api/doc_api_led.html",{"title":"Fake LED Api"},["/tp/api/doc_api_led","/tp/api/doc_api_led.md"]],
  ["v-69e7a408","/tp/ci/ci-hybride.html",{"title":"Compiler une application hybride avec Gitlab-CI"},["/tp/ci/ci-hybride","/tp/ci/ci-hybride.md"]],
  ["v-7f9c4087","/tp/ci/packager-docker.html",{"title":"Packager une application avec Docker"},["/tp/ci/packager-docker","/tp/ci/packager-docker.md"]],
  ["v-66089f84","/tp/ci/pages.html",{"title":"Utiliser GitLab Pages"},["/tp/ci/pages","/tp/ci/pages.md"]],
  ["v-32b3c3a0","/tp/cms/wordpress.html",{"title":"Installer & Configurer Wordpress"},["/tp/cms/wordpress","/tp/cms/wordpress.md"]],
  ["v-b1a71b66","/tp/cordova/",{"title":"La base de Cordova"},["/tp/cordova/index.html","/tp/cordova/README.md"]],
  ["v-40f47d80","/tp/cordova/decouverte.html",{"title":"Découverte de Cordova"},["/tp/cordova/decouverte","/tp/cordova/decouverte.md"]],
  ["v-8adf9fa0","/tp/cordova/vuejs_api_led.html",{"title":"VueJS, le réseau, et une LED"},["/tp/cordova/vuejs_api_led","/tp/cordova/vuejs_api_led.md"]],
  ["v-66c8d95a","/tp/cordova/vuejs_cordova.html",{"title":"VueJS et Cordova"},["/tp/cordova/vuejs_cordova","/tp/cordova/vuejs_cordova.md"]],
  ["v-3f8aa970","/tp/devops/alpine-vm.html",{"title":"VM Express : Alpine Linux, K3d & Docker"},["/tp/devops/alpine-vm","/tp/devops/alpine-vm.md"]],
  ["v-3b914ee2","/tp/devops/support.html",{"title":"Complément du cours Dev Ops"},["/tp/devops/support","/tp/devops/support.md"]],
  ["v-ec904c8e","/tp/docker/creer_server_local.html",{"title":"Créer des services très rapidement (et simplement)"},["/tp/docker/creer_server_local","/tp/docker/creer_server_local.md"]],
  ["v-81a1121e","/tp/docker/docker_compose.html",{"title":"Le Docker Compose"},["/tp/docker/docker_compose","/tp/docker/docker_compose.md"]],
  ["v-2e9c68e8","/tp/docker/dockerfile.html",{"title":"Les Dockerfile’s"},["/tp/docker/dockerfile","/tp/docker/dockerfile.md"]],
  ["v-6b1aa46a","/tp/docker/introduction.html",{"title":"Introduction à Docker"},["/tp/docker/introduction","/tp/docker/introduction.md"]],
  ["v-6787d6ac","/tp/git_initiation/",{"title":"Initiation GIT"},["/tp/git_initiation/index.html","/tp/git_initiation/README.md"]],
  ["v-7409463a","/tp/gitlab/",{"title":"GitLab"},["/tp/gitlab/index.html","/tp/gitlab/README.md"]],
  ["v-46cae38f","/tp/graphql/hasura.html",{"title":"Créer un serveur GraphQL"},["/tp/graphql/hasura","/tp/graphql/hasura.md"]],
  ["v-6c3ff61e","/tp/html_css/bootstrap.html",{"title":"Découverte de Bootstrap"},["/tp/html_css/bootstrap","/tp/html_css/bootstrap.md"]],
  ["v-1b00986a","/tp/html_css/integration.html",{"title":"Idée d'intégration"},["/tp/html_css/integration","/tp/html_css/integration.md"]],
  ["v-28d22b3b","/tp/html_css/maquette.html",{"title":"Maquetter un site Internet"},["/tp/html_css/maquette","/tp/html_css/maquette.md"]],
  ["v-273e7ca0","/tp/html_css/support.html",{"title":"Complément du cours CSS"},["/tp/html_css/support","/tp/html_css/support.md"]],
  ["v-27b56cfb","/tp/html_css/tailwind.html",{"title":"Découverte de Tailwind"},["/tp/html_css/tailwind","/tp/html_css/tailwind.md"]],
  ["v-6f09f9ec","/tp/html_css/tp1.html",{"title":"Découverte du HTML"},["/tp/html_css/tp1","/tp/html_css/tp1.md"]],
  ["v-6ba048ae","/tp/html_css/tp2.html",{"title":"Découverte de la CSS"},["/tp/html_css/tp2","/tp/html_css/tp2.md"]],
  ["v-68369770","/tp/html_css/tp3.html",{"title":"Mise en pratique CSS"},["/tp/html_css/tp3","/tp/html_css/tp3.md"]],
  ["v-64cce632","/tp/html_css/tp4.html",{"title":"Mise en pratique Responsive"},["/tp/html_css/tp4","/tp/html_css/tp4.md"]],
  ["v-616334f4","/tp/html_css/tp5.html",{"title":"Mon CV"},["/tp/html_css/tp5","/tp/html_css/tp5.md"]],
  ["v-8b0d221c","/tp/javascript/support.html",{"title":"Complément du cours JavaScript"},["/tp/javascript/support","/tp/javascript/support.md"]],
  ["v-70d326ae","/tp/javascript/tp1.1.html",{"title":"Des variables en veux tu en voilà !"},["/tp/javascript/tp1.1","/tp/javascript/tp1.1.md"]],
  ["v-6d697570","/tp/javascript/tp1.2.html",{"title":"Une petite mise en bouche"},["/tp/javascript/tp1.2","/tp/javascript/tp1.2.md"]],
  ["v-22f0a14c","/tp/javascript/tp1.html",{"title":"Hello World"},["/tp/javascript/tp1","/tp/javascript/tp1.md"]],
  ["v-24a579eb","/tp/javascript/tp2.html",{"title":"Le retour de Bart"},["/tp/javascript/tp2","/tp/javascript/tp2.md"]],
  ["v-d14e7332","/tp/javascript/tp3.1.html",{"title":"Interactivité"},["/tp/javascript/tp3.1","/tp/javascript/tp3.1.md"]],
  ["v-265a528a","/tp/javascript/tp3.html",{"title":"Contrôle de saisie & intéractivité"},["/tp/javascript/tp3","/tp/javascript/tp3.md"]],
  ["v-018c1974","/tp/javascript/tp4.1.html",{"title":"Pratiquer l'Ajax, adaptons un code existant"},["/tp/javascript/tp4.1","/tp/javascript/tp4.1.md"]],
  ["v-280f2b29","/tp/javascript/tp4.html",{"title":"Pratiquer l'Ajax"},["/tp/javascript/tp4","/tp/javascript/tp4.md"]],
  ["v-29c403c8","/tp/javascript/tp5.html",{"title":"Les librairies pour vous sauvez"},["/tp/javascript/tp5","/tp/javascript/tp5.md"]],
  ["v-13903327","/tp/javascript_avances/introduction.html",{"title":"Prise en main « JavaScript avancé »"},["/tp/javascript_avances/introduction","/tp/javascript_avances/introduction.md"]],
  ["v-e3344ff4","/tp/javascript_avances/revision.html",{"title":"Questions complémentaires"},["/tp/javascript_avances/revision","/tp/javascript_avances/revision.md"]],
  ["v-69a4bb41","/tp/laravel/application_todo_list.html",{"title":"Application Todo Liste"},["/tp/laravel/application_todo_list","/tp/laravel/application_todo_list.md"]],
  ["v-89744be4","/tp/laravel/authentification.html",{"title":"Laravel & l'authentification"},["/tp/laravel/authentification","/tp/laravel/authentification.md"]],
  ["v-21816fa2","/tp/laravel/creation_api.html",{"title":"TodoList : (Ré-)écrire les API du projet"},["/tp/laravel/creation_api","/tp/laravel/creation_api.md"]],
  ["v-0803c662","/tp/laravel/introduction.html",{"title":"Introduction à Laravel"},["/tp/laravel/introduction","/tp/laravel/introduction.md"]],
  ["v-3d93dff5","/tp/laravel/laravel_api.html",{"title":"Créer des API avec Laravel"},["/tp/laravel/laravel_api","/tp/laravel/laravel_api.md"]],
  ["v-12301a2e","/tp/nodejs/api.html",{"title":"Réaliser des API avec NodeJS"},["/tp/nodejs/api","/tp/nodejs/api.md"]],
  ["v-198d1cf0","/tp/nodejs/firebase.html",{"title":"Déployer du code avec Firebase"},["/tp/nodejs/firebase","/tp/nodejs/firebase.md"]],
  ["v-e6e0e0b8","/tp/openfaas/openfaas-quicky-create-faas.html",{"title":"Création d'un projet OpenFaas (Express)"},["/tp/openfaas/openfaas-quicky-create-faas","/tp/openfaas/openfaas-quicky-create-faas.md"]],
  ["v-503e2c54","/tp/openfaas/openfaas-quicky-installation-pi.html",{"title":"Création stack OpenFaas (faasd) sur un Raspberry Pi"},["/tp/openfaas/openfaas-quicky-installation-pi","/tp/openfaas/openfaas-quicky-installation-pi.md"]],
  ["v-480aeb96","/tp/openfaas/openfaas-quicky-installation.html",{"title":"Création stack OpenFaas (faasd) local via Multipass"},["/tp/openfaas/openfaas-quicky-installation","/tp/openfaas/openfaas-quicky-installation.md"]],
  ["v-4290bdb8","/tp/organisation/introduction.html",{"title":"(Ré)organiser mon code"},["/tp/organisation/introduction","/tp/organisation/introduction.md"]],
  ["v-edbf8d8a","/tp/php/support.html",{"title":"Complément du cours PHP"},["/tp/php/support","/tp/php/support.md"]],
  ["v-6ae5c8a8","/tp/php/tp-param.html",{"title":"Le passage de paramètres"},["/tp/php/tp-param","/tp/php/tp-param.md"]],
  ["v-08cd3532","/tp/php/tp1.1.html",{"title":"Le générateur de Bart"},["/tp/php/tp1.1","/tp/php/tp1.1.md"]],
  ["v-0a820dd1","/tp/php/tp1.2.html",{"title":"Utiliser des includes et une librairie"},["/tp/php/tp1.2","/tp/php/tp1.2.md"]],
  ["v-a9bc0fd6","/tp/php/tp1.html",{"title":"Créer ma première page PHP"},["/tp/php/tp1","/tp/php/tp1.md"]],
  ["v-a6525e98","/tp/php/tp2.html",{"title":"Jouer avec les formulaires"},["/tp/php/tp2","/tp/php/tp2.md"]],
  ["v-a2e8ad5a","/tp/php/tp3.html",{"title":"Structurer mon code"},["/tp/php/tp3","/tp/php/tp3.md"]],
  ["v-9f7efc1c","/tp/php/tp4.html",{"title":"Utiliser la session"},["/tp/php/tp4","/tp/php/tp4.md"]],
  ["v-d7443c0e","/tp/poo/interface.html",{"title":"Le principe des interfaces"},["/tp/poo/interface","/tp/poo/interface.md"]],
  ["v-e86f9102","/tp/python/flask.html",{"title":"Découvrir Flask"},["/tp/python/flask","/tp/python/flask.md"]],
  ["v-be0af8d6","/tp/python/flask_todolist_api.html",{"title":"Écrire des API avec Flask"},["/tp/python/flask_todolist_api","/tp/python/flask_todolist_api.md"]],
  ["v-1a05f928","/tp/rpi/web-stack.html",{"title":"Transformer un Raspberry Pi en server Web"},["/tp/rpi/web-stack","/tp/rpi/web-stack.md"]],
  ["v-77869c29","/tp/securite/",{"title":"TP Sécurité"},["/tp/securite/index.html","/tp/securite/README.md"]],
  ["v-097d7d4c","/tp/typescript/vuejs.html",{"title":"Typescript + VueJS"},["/tp/typescript/vuejs","/tp/typescript/vuejs.md"]],
  ["v-263b40da","/tp/vuejs/",{"title":"VueJS"},["/tp/vuejs/index.html","/tp/vuejs/README.md"]],
  ["v-0fa7b956","/tp/vuejs/firebase-vuejs.html",{"title":"Firebase + VueJS 2.0"},["/tp/vuejs/firebase-vuejs","/tp/vuejs/firebase-vuejs.md"]],
  ["v-b6b43202","/tp/vuejs/tp0.html",{"title":"Prise en main de VueJS 2.0"},["/tp/vuejs/tp0","/tp/vuejs/tp0.md"]],
  ["v-1cd22843","/tp/vuejs/tp1-vuejs-laravel-api.html",{"title":"Ajouter VueJS 2.0 dans un site existant"},["/tp/vuejs/tp1-vuejs-laravel-api","/tp/vuejs/tp1-vuejs-laravel-api.md"]],
  ["v-b34a80c4","/tp/vuejs/tp1.html",{"title":"Ajouter VueJS 2.0 dans une application existante"},["/tp/vuejs/tp1","/tp/vuejs/tp1.md"]],
  ["v-afe0cf86","/tp/vuejs/tp2.html",{"title":"Réaliser une application avec VueJS 2.0"},["/tp/vuejs/tp2","/tp/vuejs/tp2.md"]],
  ["v-cb152c3a","/tp/vuejs/vuetify-vuejs.html",{"title":"Vuetify + VueJS 2.0"},["/tp/vuejs/vuetify-vuejs","/tp/vuejs/vuetify-vuejs.md"]],
  ["v-7344ee54","/tp/vuejs3/petite-vue.html",{"title":"Petite Vue : La réactivité simplifiée"},["/tp/vuejs3/petite-vue","/tp/vuejs3/petite-vue.md"]],
  ["v-d173a9f8","/tp/vuejs3/vite.html",{"title":"Découverte de VueJS 3.0 (avec ViteJS)"},["/tp/vuejs3/vite","/tp/vuejs3/vite.md"]],
  ["v-66344e42","/cours/demo/vuejs/12vue.html",{"title":"1-2 Vue"},["/cours/demo/vuejs/12vue","/cours/demo/vuejs/12vue.md"]],
  ["v-2ef23b99","/cours/demo/vuejs/clock.html",{"title":"Horloge"},["/cours/demo/vuejs/clock","/cours/demo/vuejs/clock.md"]],
  ["v-243e7aeb","/cours/demo/vuejs/counter.html",{"title":"Compteur"},["/cours/demo/vuejs/counter","/cours/demo/vuejs/counter.md"]],
  ["v-5d6bfcf9","/cours/demo/vuejs/demo1.html",{"title":"Démo 1"},["/cours/demo/vuejs/demo1","/cours/demo/vuejs/demo1.md"]],
  ["v-4cdf7190","/cours/demo/vuejs/sound.html",{"title":"Sonomètre"},["/cours/demo/vuejs/sound","/cours/demo/vuejs/sound.md"]],
  ["v-141fd4fb","/cours/demo/vuejs/timestamp-color.html",{"title":"Horloge 2"},["/cours/demo/vuejs/timestamp-color","/cours/demo/vuejs/timestamp-color.md"]],
  ["v-5b0f2b97","/tp/ci/firebase/functions.html",{"title":"Déploiement continue d'un projet Firebase (function, web, …)"},["/tp/ci/firebase/functions","/tp/ci/firebase/functions.md"]],
  ["v-1a33b904","/tp/ci/gitlab/runner.html",{"title":"Installation & Configuration d'un Runner"},["/tp/ci/gitlab/runner","/tp/ci/gitlab/runner.md"]],
  ["v-20bddf8c","/tp/ci/jamstack/netlify.html",{"title":"Build, Deploy avec Netlify"},["/tp/ci/jamstack/netlify","/tp/ci/jamstack/netlify.md"]],
  ["v-4c50482b","/tp/ci/kubernetes/cd-avec-kubernetes.html",{"title":"Livraison continue, Gitlab-CI + Kubernetes"},["/tp/ci/kubernetes/cd-avec-kubernetes","/tp/ci/kubernetes/cd-avec-kubernetes.md"]],
  ["v-bbff927a","/tp/ci/kubernetes/deploy-container-in-kubernetes.html",{"title":"Déployer une Image Docker dans Kubernetes"},["/tp/ci/kubernetes/deploy-container-in-kubernetes","/tp/ci/kubernetes/deploy-container-in-kubernetes.md"]],
  ["v-05c259ec","/tp/devops/sonarqube/sonarqube.html",{"title":"SonarQube"},["/tp/devops/sonarqube/sonarqube","/tp/devops/sonarqube/sonarqube.md"]],
  ["v-8f299b06","/tp/ci/ci-test/tests.html",{"title":"Tester en continu"},["/tp/ci/ci-test/tests","/tp/ci/ci-test/tests.md"]],
  ["v-6afd4caa","/tp/git_initiation/solution/",{"title":"Initiation GIT."},["/tp/git_initiation/solution/index.html","/tp/git_initiation/solution/README.md"]],
  ["v-3e70e207","/tp/php/mvc/tp1.1.html",{"title":"Prise en main structure MVC"},["/tp/php/mvc/tp1.1","/tp/php/mvc/tp1.1.md"]],
  ["v-0e04d62a","/tp/php/mvc/tp1.html",{"title":"Structure de développement MVC"},["/tp/php/mvc/tp1","/tp/php/mvc/tp1.md"]],
  ["v-5d7a3b5c","/tp/php/sql/support.html",{"title":"Complément Cours Base de données"},["/tp/php/sql/support","/tp/php/sql/support.md"]],
  ["v-1dc0d59c","/tp/php/sql/tp5.html",{"title":"Bart PHP et MySQL"},["/tp/php/sql/tp5","/tp/php/sql/tp5.md"]],
  ["v-1a57245e","/tp/php/sql/tp6.html",{"title":"Greta TV - Administrable"},["/tp/php/sql/tp6","/tp/php/sql/tp6.md"]],
  ["v-5bbdd9b4","/tp/php/mvc/dashboard/tp0.html",{"title":"Définition du projet"},["/tp/php/mvc/dashboard/tp0","/tp/php/mvc/dashboard/tp0.md"]],
  ["v-58542876","/tp/php/mvc/dashboard/tp1.html",{"title":"La réalisation"},["/tp/php/mvc/dashboard/tp1","/tp/php/mvc/dashboard/tp1.md"]],
  ["v-3706649a","/404.html",{},["/404"]],
]

export const pagesRoutes = routeItems.reduce(
  (result, [name, path, meta, redirects]) => {
    result.push(
      {
        name,
        path,
        component: Vuepress,
        meta,
      },
      ...redirects.map((item) => ({
        path: item,
        redirect: path,
      }))
    )
    return result
  },
  [
    {
      name: "404",
      path: "/:catchAll(.*)",
      component: Vuepress,
    }
  ]
)
